#ifndef MQTT_CONFIG_TEMPLATE_H
#define MQTT_CONFIG_TEMPLATE_H

// MQTT Configuration Settings
#define MQTT_BROKER    "YOUR_MQTT_BROKER_ADDRESS"
#define MQTT_PORT      "YOUR_MQTT_BROKER_PORT"
#define MQTT_CLIENT_ID "YOUR_MQTT_CLIENT_ID"
#define MQTT_USERNAME  "YOUR_MQTT_USERNAME"
#define MQTT_PASSWORD  "YOUR_MQTT_PASSWORD"
#define MQTT_TOPIC     "YOUR_MQTT_TOPIC"

#endif
